### ISSUE TITLE
Feature Request: Output slumber start to console

### ISSUE THREAD

**Issue by ArtanizAvi** [QPCrummer/Slumber#5]
This is not an issue, but a feature request.

When Slumber activates, output a message to console so the slumber command doesn't need to be run to make sure it started. If you could also enable the slumber command to show if its on, how long it has been active for.

**Comment by QPCrummer** [comment]
@ArtanizAvi Sorry for the extremely late response to this issue.
This feature has been added in version 1.1.3 https://modrinth.com/mod/slumber/version/1.1.3

To enable the Slumber debug messages, go into the config and set `debug-messages` to `true`.
By enabling this, it will also give you the time that the server has been frozen for. This is given in seconds. So basically it will save when the server has been frozen, and then when someone joins the server, it will give an output to how long the server has been frozen for. 

If this is not what you wanted, or you do specifically want the command to give an instantaneous time since it was last frozen, please let me know 👍 I will not be marking this issue as complete yet till I receive some feedback from you. Thank you for making this suggestion for the mod, I appreciate it!

**Comment by ArtanizAvi** [comment]
This is pretty much what I wanted. Thank you very much for getting it out so quickly!
