### ISSUE TITLE
Bug: Server is still frozen once joining the server

### ISSUE THREAD

**Issue by Rikthepixel** [QPCrummer/Slumber#8]
## Mod Version
v1.1.2

## Minecraft Version
1.20.1

## Mod Loader
Fabric

## Other installed mods
fabric-api
carpet

## Expected behavior 
Once joining the server a player can pick up block, interact with mobs, and mobs should move.

## Actual behavior
The server seems to be stuck in a frozen state where players cannot interact with entities like pigs, skeletons, etc. but they can place blocks.

### Symptoms
https://github.com/Tater-Certified/Slumber/assets/63408969/dbaf15de-5db7-48b1-b1cf-82f0804e8ad3

https://github.com/Tater-Certified/Slumber/assets/63408969/6fb6a2ef-08eb-4310-a09b-6ef7c6cbe865

### Server log
![image](https://github.com/Tater-Certified/Slumber/assets/63408969/ee266ee8-e414-4bd8-ac33-d46b5f8a7f24)

## Attempts to fix
- Reinstalling the mod
- Restarting the server

Once removing the slumber mod it seems to not freeze. Version 1.1.1 seems to not have this issue.

## Note:
Thanks for making this, it actually seems to decrease the CPU usage on my home server. Super useful since I am using it to host some other projects too. So, thank you guys for putting in the work, I appreciate ya ❤️

**Comment by QPCrummer** [comment]
Well, V1.1.1 didn’t work at all :p. I find this extremely interesting since it was working perfectly fine on my test server before I released it. I even tested players joining and leaving. Also it said that the server is overloaded… that can’t be true if the server is truly frozen. Perhaps there is an issue with my mod and some other mod that causes it to stall? I’ll look at this in more depth in a few hours. Thank you for reporting this!

**Comment by Rikthepixel** [comment]
Maybe it has to do with my environment. I am running it in docker, using the "tzg/minecraft-server:java17-alpine" image. 

I am not sure if it is a different mod that is doing it, since I am only using fabric, fabric-api and carpet. 

As for the server getting overloaded, the statistics seem to indicate once a user joins the CPU usage spikes and then goes back to frozen levels. So it does seem to freeze the server, unfreezes and then freezes again.

I wish I could be of more use, but I am not familiar with Java and Fabric development

**Comment by QPCrummer** [comment]
The issue is that it should never be possible to freeze the server while players are online as I specifically check this. I mean, I see the issue in question, but I don’t understand why or how this could ever happen. 

One thing you could try for me is if you think the server is frozen, try running the “/tick freeze” command and see if the server starts running as normal. If so, that basically proves that there is something wrong with my sleep-tracking logic.

**Comment by Rikthepixel** [comment]
Okey an update, it does seem that after I execute the `/tick freeze` command it outputs "Game runs normally". 

After that once attempting to break and pick up a block, it allowed me to pick it up.

Here is a video:

https://github.com/Tater-Certified/Slumber/assets/63408969/22107d22-eb4b-4bbe-9df9-5487caaa3b42

**Comment by QPCrummer** [comment]
@Rikthepixel I have fixed the issue in 1.1.3 https://modrinth.com/mod/slumber/version/1.1.3

So basically what happened was you actually don't have my mod enabled at all :P
In the config I have a "toggle" that is set to disabled by default (which is now enabled by default in 1.1.3). You can also enable it with `/slumber true`. The issue was that you *did* have `safe-starting` enabled, which freezes the server while the terrain is loading to help prevent redstone machines from breaking if they are loaded incorrectly. Now my freeze method in my mod checks if the mod is toggled on if you want to freeze or unfreeze the server. The `safe-starting` method doesn't use this method, but when I want to continue freezing after the server has started, it *does* use this method. Since you had the `toggle` set to false, it was unable to freeze *and unfreeze* the server. 
This has now been fixed in 1.1.3 as it was a large oversight on my part. Thank you a lot for reporting this to me, it means a lot!
Once you test version 1.1.3, feel free to close this issue if the mod works as expected 👍

**Comment by Rikthepixel** [comment]
Great work! When starting up the server it seems to be working like expected!

Thank you a lot!
